using SaferPay.Models.Attributes;

namespace SaferPay.Models.Core;

/// <summary>
/// Issuer reference information
/// </summary>
public class IssuerReference
{

    /// <summary>
    /// Mastercard Transaction Link ID (TLID) is a unique identifier generated by Mastercard for each payment. It is used in all subsequent actions related to the original payment, including Merchant Initiated Transactions (MIT).<br/><br/>
    /// TLID is a 22-character, case-sensitive UUID made up of uppercase and lowercase alphabetic, numeric, and special characters in random order, with no spaces allowed.
    /// </summary>
    public string MastercardTLID { get; set; }


    /// <summary>
    /// SCA transaction settlement date, created by the card issuer. For MasterCard schemes only.<br/><br/>
    /// <i>String length: inclusive between 4 and 4</i><br/>
    /// <i>Example: 0122</i>
    /// </summary>
    public string SettlementDate { get; set; }


    /// <summary>
    /// SCA transaction stamp, created by the card issuer<br/><br/>
    /// <i>Max length: 50</i><br/>
    /// <i>Example: 9406957728464714731817</i>
    /// </summary>
    [Mandatory("TransactionStamp is required!")]
    public string TransactionStamp { get; set; }


}
