using SaferPay.Enums;
using SaferPay.Models.Attributes;

namespace SaferPay.Models.Core;

/// <summary>
/// Controls whether the given means of payment should be stored inside the Saferpay Secure Card Data storage.
/// </summary>
public class RegisterAlias
{
    /// <summary>
    /// Alias id to be used for registration if not generated by Saferpay. Mandatory if IdGenerator is 'MANUAL'. This value is case-insensitive.<br/><br/>
    /// <i>Id[1..40]<br/>
    /// Example: alias35nfd9mkzfw0x57iwx</i>
    /// </summary>
    public string Id { get; set; }

    /// <summary>
    /// Id generator to be used by Saferpay.<br/><br/>
    /// <i>Possible values: MANUAL, RANDOM, RANDOM_UNIQUE.</i>
    /// </summary>
    [Mandatory("IdGenerator field is mandatory.")]
    public IdGeneratorTypes IdGenerator { get; set; }

    /// <summary>
    /// Number of days this card is to be stored within Saferpay. If not filled, the default lifetime (1096 days) will be used.<br/><br/>
    /// <i>Range: inclusive between 1 and 1600<br/>
    /// Example: 1000</i>
    /// </summary>
    public int Lifetime { get; set; }

}