using Newtonsoft.Json;

namespace SaferPay.Models.Core;

/// <summary>
/// General information about the request.
/// </summary>
public class RequestHeader
{
    /// <summary>
    /// Version number of the interface specification. For new implementations, the newest Version should be used.
    /// <br/>Possible values: 1.43
    /// </summary>
    public string SpecVersion { get; set; }

    /// <summary>
    /// Saferpay customer id. Part of the Saferpay AccountID, which has the following format: 123123-12345678. The first Value is your CustomerID.
    /// </summary>
    public string CustomerId { get; set; }


    /// <summary>
    /// Id generated by merchant system, for debugging purposes. Should be unique for each new request. If a request is retried due to an error, use the same request id. In this case, the RetryIndicator should be increased instead, to indicate a subsequent attempt.
    /// </summary>
    public string RequestId { get; set; }

    /// <summary>
    /// 0 if this specific request is attempted for the first time, >=1 if it is a retry.<br/><br/>
    /// <i>Range: inclusive between 0 and 9</i> <br/>
    /// <i>Example: 0</i>
    /// </summary>
    public int RetryIndicator { get; set; } = 0;

    /// <summary>
    /// Information about the caller (merchant host)
    /// </summary>
    [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
    public ClientInfo ClientInfo { get; set; }


}